package Entity

enum class ObjetLabel(val label: String, val id: Int) {
    PERSON("person", 1),
    BICYCLE("bicycle", 2),
    CAR("car", 3),
    MOTORCYCLE("motorcycle", 4),
    AIRPLANE("airplane", 5),
    BUS("bus", 6),
    TRAIN("train", 7),
    TRUCK("truck", 8),
    BOAT("boat", 9),
    TRAFFIC_LIGHT("traffic light", 10),
    FIRE_HYDRANT("fire hydrant", 11),
    STOP_SIGN("stop sign", 12),
    PARKING_METER("parking meter", 13),
    BENCH("bench", 14),
    BIRD("bird", 15),
    CAT("cat", 16),
    DOG("dog", 17),
    HORSE("horse", 18),
    SHEEP("sheep", 19),
    COW("cow", 20),
    ELEPHANT("elephant", 21),
    BEAR("bear", 22),
    ZEBRA("zebra", 23),
    GIRAFFE("giraffe", 24),
    BACKPACK("backpack", 25),
    UMBRELLA("umbrella", 26),
    HANDBAG("handbag", 27),
    TIE("tie", 28),
    SUITCASE("suitcase", 29),
    FRISBEE("frisbee", 30),
    SKIS("skis", 31),
    SNOWBOARD("snowboard", 32),
    SPORTS_BALL("sports ball", 33),
    KITE("kite", 34),
    BASEBALL_BAT("baseball bat", 35),
    BASEBALL_GLOVE("baseball glove", 36),
    SKATEBOARD("skateboard", 37),
    SURFBOARD("surfboard", 38),
    TENNIS_RACKET("tennis racket", 39),
    BOTTLE("bottle", 40),
    WINE_GLASS("wine glass", 41),
    CUP("cup", 42),
    FORK("fork", 43),
    KNIFE("knife", 44),
    SPOON("spoon", 45),
    BOWL("bowl", 46),
    BANANA("banana", 47),
    APPLE("apple", 48),
    SANDWICH("sandwich", 49),
    ORANGE("orange", 50),
    BROCCOLI("broccoli", 17),
    CARROT("carrot", 17),
    HOT_DOG("hot dog", 17),
    PIZZA("pizza", 17),
    DONUT("donut", 17),
    CAKE("cake", 17),
    CHAIR("chair", 17),
    COUCH("couch", 17),
    POTTED_PLANT("potted plant", 17),
    BED("bed", 17),
    DINING_TABLE("dining table", 17),
    TOILET("toilet", 17),
    TV("tv", 17),
    LAPTOP("laptop", 17),
    MOUSE("mouse", 17),
    REMOTE("remote", 17),
    KEYBOARD("keyboard", 17),
    CELL_PHONE("cell phone", 17),
    MICROWAVE("microwave", 17),
    OVEN("oven", 17),
    TOASTER("toaster", 17),
    SINK("sink", 17),
    REFRIGERATOR("refrigerator", 17),
    BOOK("book", 17),
    CLOCK("clock", 17),
    VASE("vase", 17),
    SCISSORS("scissors", 17),
    TEDDY_BEAR("teddy bear", 17),
    HAIR_DRIER("hair drier", 17),
    TOOTHBRUSH("toothbrush", 17);

    companion object {
        private val map = ObjetLabel.values().associateBy(ObjetLabel::label)
        fun fromLabel(label: String): ObjetLabel = map.getValue(label)
    }
}